name: CLA Signature
description: Template for issues triggering CLA signature
title: CLA signature
labels:
  - cla-signing
assignees:
  - C-nit
  - christofid
  - drugilsberg
  - jannisborn
  - kwehden
body:
  - type: checkboxes
    id: cla
    attributes:
      label: Contributor License Agreement
      description: Sign CLA via GitHub issue
      options:
        - label: I accept and sign the contributor license agreement ([CLA](../../CONTRIBUTING.md#contributor-license-agreement)) to contribute to GT4SD.
          required: true
  - type: input
    attributes:
      label: Linking the PR where the contributor should be added.
      placeholder: "#33"
  - type: markdown
    attributes:
      value: |
        Submitting this issue with the checkbox ticked will add you to the list of contributors.
        By default this will be done on the main branch, so that you may need to merge the main branch into your open PR.

# github.event.issue.body
# Idea: checkbox
# submission works on pr with "closes #<this issue>
# merging pr will close the issue.
