name: CLA signature

on:
  issues:
    types: [opened]

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: View issue information
        run: |
          echo "Issue: ${{ github.event.issue }}"
      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  cla:
    if: ${{ github.event.issue.name == 'CLA Signature' }}
    # This issue can only be opened if the CLA signing checkbox is ticked
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Adding user to contributors
        run: |
          echo Signature by ${{ github.event.issue.user.login }}
          git clone https://github.com/GT4SD/gt4sd-core --branch main --single-branch gt4sd-core-main
          cd gt4sd-core-main
          echo $(jq '.contributors |= (. + ["${{ github.event.issue.user.login }}"] | unique)' .clabot) > .clabot
          echo Updated .clabot:
          echo $(cat .clabot)
          git config --local user.email "gt4sd-actions@github.com"
          git config --local user.name "GitHub Action"
          git add .clabot
          git commit -m "chore: adding ${{ github.event.issue.user.login }} as contributor." -a || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          directory: gt4sd-core-main
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Store commit hash
        id: last_commit_hash
        run: |
          echo "last_commit_hash=$(git rev-parse HEAD | cut -c 1-8)" >> $GITHUB_ENV
      - name: Mark signature in the issue
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: cla-signed
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            Contributor was added: ${{ env.last_commit_hash }}.
            Note that your PR may be still be blocked until this is merged into your branch.
